# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arbokraft
email: abrokraft+web@hurel.info
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: arbokraft
github_username:  arbokraft

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  exercices:
      output: true
      permalink: /:collection/:path/
  resources:
      output: true
      permalink: /:collection/:path/
  objectlist:
      output: true
      permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "exercices"
      type: "exercices"
    values:
      layout: "post"
      author: "Arbokraft"
  -
    scope:
      path: "resources"
      type: "resources"
    values:
      layout: "ressources"
      author: "Arbokraft"
# Serving
detach:  false
port:    4000
host:    192.168.168.203